sudo: required
services:
  - docker

before_install:
  - docker build -t petivagyok16/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run petivagyok16/react-test npm test -- --coverage

after_success:
  - docker build -t petivagyok16/multi-client ./client
  - docker build -t petivagyok16/multi-nginx ./nginx
  - docker build -t petivagyok16/multi-server ./server
  - docker build -t petivagyok16/multi-worker ./worker
  
  # Log into DockerCLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to DockerHUB
  - docker push petivagyok16/multi-client
  - docker push petivagyok16/multi-nginx
  - docker push petivagyok16/multi-server
  - docker push petivagyok16/multi-worker

